---
- name: Print linux distribution and version
  hosts: all
  tasks:
    - name: Capture output of id command
      command: echo
      ignore_errors: yes
      register: login

    - name: Print Linux distribution and version
      debug:
        msg:
          - "Distribution: {{ ansible_distribution }}"
          - "Major Version: {{ ansible_distribution_major_version }}"

    - name: Include yum orchestration playbooks based on distribution and version
      include_tasks: "{{ item }}"
      when: 
        - ansible_distribution == "CentOS"
        - ansible_distribution_major_version == item.version
      loop:
        - { file: "yum6_orch.yml", version: "6" }
        - { file: "yum7_orch.yml", version: "7" }
